server:
  port: 8092
mybatis:
  mapper-locations: classpath:mapping/*.xml
spring:
  datasource:
    name: songs
    url: jdbc:mysql://localhost:3306/songs?characterEncoding=utf-8&useSSL=false
    username: root
    password: kaikai
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
  application:
    name: VIEW-SERVICE
  cache:
    type: REDIS
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    pool:
      max-active: 100
      max-idle: 10
      max-wait: 100000
    lettuce:
      shutdown-timeout: 0
    timeout: 5000
    database: 0

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

#redis:
#  database: 0           # Redis服务器数据库
#  host: 127.0.0.1    # Redis服务器地址
#  port: 6379            # Redis服务器连接端口
#  password:      # Redis服务器连接密码（默认为空）
#  timeout: 6000ms       # 连接超时时间（毫秒）
#  jedis:
#    pool:
#      max-active: 200   # 连接池最大连接数（使用负值表示没有限制）
#      max-wait: -1      # 连接池最大阻塞等待时间（使用负值表示没有限制）
#      max-idle: 10      # 连接池中的最大空闲连接
#      min-idle: 0       # 连接池中的最小空闲连接
##eureka:
#  client:
#    service-url:
##      defaultZone: http://10.111.229.84:8761/eureka
#      defaultZone: http://192.168.0.101:8761//eureka
#
#ribbon:
#  ReadTimeout: 6000000
#  ConnectTimeout: 6000000
#feign:
#  client:
#    config:
#      defualt:
#        connectTimeout: 20000
#        readTimeout: 20000
